//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CreditCardId { get; set; }
        public string CardHolder { get; set; }
        public string CardExpiry { get; set; }
        public long CardNumber { get; set; }
        public int CVC { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
