//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuredVehicle_Has_Driver
    {
        public int InsuredVehicleId { get; set; }
        public int DriverId { get; set; }
        public int InsuredVehicleHasDriverId { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual VehicleInsured VehicleInsured { get; set; }
    }
}
