//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paypal
    {
        public int PaypalId { get; set; }
        public string PaypalEmail { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
