//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInsured
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInsured()
        {
            this.InsuredVehicle_Has_Driver = new HashSet<InsuredVehicle_Has_Driver>();
        }
    
        public int VehicleInsured1 { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public int Year { get; set; }
        public int InsuranceId { get; set; }
    
        public virtual Insurance Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuredVehicle_Has_Driver> InsuredVehicle_Has_Driver { get; set; }
    }
}
